Vagrant.configure("2") do |config|

	# Specify the base box
	config.vm.box = "ubuntu/trusty64"
	#  config.vm.box = "ubuntu/trusty32"
	# config.vm.box = "hashicorp/precise32"


	# Setup port forwarding
	#  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
	#  config.vm.network :forwarded_port, guest: 443, host: 8443, auto_correct: true
	#    config.vm.network :public_network, type: "dhcp", :bridge => 'eth0'
	#    config.vm.network :public_network, type: "dhcp", :bridge => 'wlan0'
	config.vm.network "private_network", type: "dhcp"

	# Setup synced folder
	#config.vm.synced_folder "./", "/share", create: true, group: "www-data", owner: "www-data"

	# VM specific configs
	config.vm.provider "virtualbox" do |v|
		v.name = "Armbuilder"
		v.memory = 4096
		v.cpus = 2
	end

	# Shell provisioning
	config.vm.provision "shell" do |s|
		s.path = "initialize.sh"   
	end
end
