Vagrant.configure("2") do |config|

	# Specify the base box
	config.vm.box = "ubuntu/xenial64"

	# Setup port forwarding
	config.vm.network "private_network", type: "dhcp"
	config.vm.network "public_network", ip: "141.13.92.73", bridge: "eth0"
	#config.vm.network "public_network", type: "dhcp", bridge: "eth5"
 	config.vm.box_check_update = true	
	# default router
	config.vm.provision "shell",
		run: "always",
		inline: "route add default gw 141.13.92.125"

	# VM specific configs
	config.vm.provider "virtualbox" do |v|
		v.gui = true
		v.name = "Armbuilder"
		v.memory = 4096
		v.cpus = 4
	end

	# Shell provisioning
	config.vm.provision "shell" do |s|
		s.path = "initialize.sh"   
	end
	#config.ssh.username = "vagrant"
end
